server:
  port: 8060

spring:
  application:
    name: zuul

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/
zuul:
  routes:
    api-a:
          path: /api-a/**
          serviceId: ribbon
    api-b:
          path: /api-b/**
          serviceId: feign


